version: "3.9"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
      - target: 53
        published: 53
        protocol: udp
      - target: 67
        published: 67
        protocol: udp
      - target: 80
        published: 81
    environment:
      TZ: "Africa/Johannesburg"
    volumes:
      - "/internalStorage/pihole/pihole:/etc/pihole/"
      - "/internalStorage/pihole/dnsmasq:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - target: 7878
        published: 7878
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Africa/Johannesburg
    volumes:
      - /internalStorage/radarr/config:/config
      - /internalStorage/downloads:/downloads
      - /home/callum/media/Movies:/movies

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - target: 9117
        published: 9117
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Africa/Johannesburg
    volumes:
      - /internalStorage/jackett/config:/config

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - target: 8989
        published: 8989
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Africa/Johannesburg
    volumes:
      - /internalStorage/sonarr/config:/config
      - /internalStorage/downloads:/downloads
      - /home/callum/media/Series:/series

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /internalStorage/deluge/config:/config
      - /internalStorage/downloads:/downloads
    ports:
      - target: 8112
        published: 8112
      - target: 6881
        published: 6881
      - target: 6881
        published: 6881
        protocol: udp
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports:
      - target: 32400
        published: 32400
    environment:
      - TZ=Africa/Johannesburg
      - PLEX_CLAIM=claim-vt7fbMsz6Eq2WsKpkpiR
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - /internalStorage/config:/config
      - /internalStorage/transcode:/transcode
      - /home/callum/media/Series:/data/series
      - /home/callum/media/Movies:/data/movies
    restart: unless-stopped

  nginx:
    build:
      dockerfile: ../docker/nginx/Dockerfile
      context: ./frontend
    container_name: nginx
    ports:
      - target: 80
        published: 80
    depends_on:
      - plex
      - deluge
      - sonarr
      - jackett
      - radarr
      - pihole
    restart: unless-stopped
