version: "3.9"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Africa/Johannesburg'
    volumes:
      - 'D:/dockertesting/pihole/pihole:/etc/pihole/'
      - 'D:/dockertesting/pihole/dnsmasq:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
    - 7878:7878
    volumes:
    - D:/dockertesting/radarr/config:/config
    - D:/dockertesting/downloads:/downloads
    - D:/dockertesting/radarr/movies:/movies
    environment:
    - PUID=1000
    - PGID=150
    - TZ=Africa/Johannesburg
    image: linuxserver/radarr:latest

  jackett:
    container_name: jackett
    restart: unless-stopped
    ports:
    - 9117:9117
    volumes:
    - D:/dockertesting/jackett/config:/config
    environment:
    - PUID=1000
    - PGID=150
    - TZ=Africa/Johannesburg
    image: linuxserver/jackett

 
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
    - 8989:8989
    volumes:
    - D:/dockertesting/sonarr/config:/config
    - D:/dockertesting/downloads:/downloads
    - D:/dockertesting/sonarr/movies:/movies
    environment:
    - PUID=1000
    - PGID=150
    - TZ=Africa/Johannesburg
    image: linuxserver/sonarr:latest
 
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - D:/dockertesting/deluge/config:/config
      - D:/dockertesting/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

#  plex:
#   image: ghcr.io/linuxserver/plex:latest
#   container_name: plex
#   network_mode: host
#   ports:
#     - "32400:32400"
#   environment:
#     - PUID=1000
#     - PGID=1000
#     - VERSION=docker 
#     - TZ=Africa/Johannesburg
#   volumes:
#     - D:/plextest/config:/config
#     - D:/plextest/series:/tv
#     - D:/plextest/movies:/movies
#   restart: unless-stopped


  